### ISSUE TITLE
rolling docker image

### ISSUE THREAD

**Issue by sevki** [GoogleCloudPlatform/traffic-director-grpc-bootstrap#21]
hey folks, are there any plans to have a rolling image for this repo?
`0.12.0-rc1` was released on Apr 22, 2021, it'd be nice to have a latest :)

**Comment by ejona86** [comment]
Huh, I missed the email notification for this.

`0.12.0-rc1` was an RC, so it was really only intended for testing.

By rolling image, do you mean a `latest` tag so that you can always be on the latest? If so, then no. That would mean a single problem on our side could impact a wide number of users. Upgrades shouldn't happen arbitrarily in production, and I don't think many people would incorporating our image as the base for their images.

If there's a common approach that lets you pin to the current `lastest` and you need to re-run a command/rebuild/something-else to update the pin, then I think we'd be more interested.

I do agree it is annoying to manually update dependencies. But it's also annoying when deployments to production break suddenly because of a regression in a release.

**Comment by ejona86** [comment]
We could add a `testing` (or similar) tag that would point to the latest release. That would probably be okay. The main thing is to not use it during production, and "testing" would make that clear enough.

@sevki, would that work for you?
